#pragma once

#include <stdint.h>
#include "constants.h"

enum TextType
{
	INVALID_TEXT,
	DEBUG_TEXT,
	ETC_TEXT,
	MARKETING_PHONE_1,
	MARKETING_PHONE_2,
	MARKETING_PHONE_2_A,
	MARKETING_PHONE_2_A_1,
	MARKETING_PHONE_2_B,
	MARKETING_PHONE_2_B_1,
	MARKETING_PHONE_2_B_2,
	MARKETING_PHONE_3,
	MARKETING_PHONE_3_A,
	MARKETING_PHONE_3_A_1,
	MARKETING_PHONE_3_B,
	MARKETING_PHONE_3_B_1,
	MARKETING_PHONE_3_B_2,
	MARKETING_PHONE_4,
	MARKETING_PHONE_5,
	MARKETING_PHONE_6,
	MARKETING_PHONE_7,
	MARKETING_PHONE_7_A,
	MARKETING_PHONE_7_A_1,
	MARKETING_PHONE_7_B,
	MARKETING_PHONE_7_C_LOW_TENSION,
	MARKETING_PHONE_7_C_HIGH_TENSION,
	MARKETING_PHONE_8,
	MARKETING_PHONE_9,
	MARKETING_PHONE_10,
	MARKETING_PHONE_11,
	MARKETING_PHONE_11_A,
	MARKETING_PHONE_11_A_1,
	MARKETING_PHONE_11_B_LOW_TENSION,
	MARKETING_PHONE_11_B_HIGH_TENSION,
	MARKETING_PHONE_11_B_1,
	MARKETING_PHONE_12,
	MARKETING_PHONE_13,
	MARKETING_PHONE_14,
	MARKETING_PHONE_14_A,
	MARKETING_PHONE_14_B,
};

enum TextTensionType
{
	NORMAL_TENSION,
	HIGH_TENSION,
	FATAL_TENSION,
};

struct TextDTO
{
	char* text = nullptr;
	uint8_t playerTensionDelta = 0;
	TextTensionType tensionType = NORMAL_TENSION;

	TextDTO(char* text, uint8_t playerTensionDelta = 0, TextTensionType tensionType = NORMAL_TENSION)
	{
		this->text = text;
		this->playerTensionDelta = playerTensionDelta;
		this->tensionType = tensionType;
	}
};

TextDTO getTextInfo(TextType textTye);