#pragma once

enum TextType
{
	INVALID_TEXT,
	DEBUG_TEXT,
	ETC_TEXT,
	ROSTOV_MARKETING_PHONE_1,
	ROSTOV_MARKETING_PHONE_2,
	ROSTOV_MARKETING_PHONE_2_1,
	ROSTOV_MARKETING_PHONE_2_2,
	ROSTOV_MARKETING_PHONE_3,
	ROSTOV_MARKETING_PHONE_4,
	ROSTOV_MARKETING_PHONE_4_1,
	ROSTOV_MARKETING_PHONE_4_2,
	ROSTOV_MARKETING_PHONE_4_3,
};

const char* getText(TextType textTye);