#pragma once

#include <stdint.h>
#include "constants.h"

enum TextType
{
	INVALID_TEXT,
	DEBUG_TEXT,
	ETC_TEXT,
	// Marketing dialogue
	MARKETING_PHONE_1,
	MARKETING_PHONE_2,
	MARKETING_PHONE_2_A,
	MARKETING_PHONE_2_A_1,
	MARKETING_PHONE_2_B,
	MARKETING_PHONE_2_B_1,
	MARKETING_PHONE_2_B_2,
	MARKETING_PHONE_2_C,
	MARKETING_PHONE_2_C_1,
	MARKETING_PHONE_2_C_2,
	MARKETING_PHONE_2_C_3,
	MARKETING_PHONE_2_C_4,
	MARKETING_PHONE_2_C_4_A,
	MARKETING_PHONE_2_C_4_B,
	MARKETING_PHONE_3,
	MARKETING_PHONE_3_A,
	MARKETING_PHONE_3_A_1,
	MARKETING_PHONE_3_B,
	MARKETING_PHONE_3_B_1,
	MARKETING_PHONE_3_B_2,
	MARKETING_PHONE_4,
	MARKETING_PHONE_5,
	MARKETING_PHONE_6,
	MARKETING_PHONE_7,
	MARKETING_PHONE_7_A,
	MARKETING_PHONE_7_A_1,
	MARKETING_PHONE_7_B,
	MARKETING_PHONE_7_C_LOW_TENSION,
	MARKETING_PHONE_7_C_HIGH_TENSION,
	MARKETING_PHONE_8,
	MARKETING_PHONE_9,
	MARKETING_PHONE_10,
	MARKETING_PHONE_11,
	MARKETING_PHONE_11_A,
	MARKETING_PHONE_11_A_1,
	MARKETING_PHONE_11_B_LOW_TENSION,
	MARKETING_PHONE_11_B_HIGH_TENSION,
	MARKETING_PHONE_11_B_1,
	MARKETING_PHONE_12,
	MARKETING_PHONE_13,
	MARKETING_PHONE_14,
	MARKETING_PHONE_14_A,
	MARKETING_PHONE_14_B,
	// Starting dialogue with dad
	ONE_DAD_PHONE_1,
	ONE_DAD_PHONE_2,
	ONE_DAD_PHONE_2_A,
	ONE_DAD_PHONE_2_B,
	ONE_DAD_PHONE_3,
	ONE_DAD_PHONE_3_A,
	ONE_DAD_PHONE_3_A_1,
	ONE_DAD_PHONE_3_A_2,
	ONE_DAD_PHONE_3_A_2_A,
	ONE_DAD_PHONE_3_A_2_B,
	ONE_DAD_PHONE_3_A_2_C,
	ONE_DAD_PHONE_3_A_3,
	ONE_DAD_PHONE_3_B,
	ONE_DAD_PHONE_3_B_1,
	ONE_DAD_PHONE_3_B_2,
	ONE_DAD_PHONE_3_B_3,
	ONE_DAD_PHONE_3_B_3_A,
	ONE_DAD_PHONE_3_B_3_B,
	ONE_DAD_PHONE_3_B_4,
	ONE_DAD_PHONE_3_B_5,
	ONE_DAD_PHONE_4,
	ONE_DAD_PHONE_4_A,
	ONE_DAD_PHONE_4_B,
	ONE_DAD_PHONE_4_C,
	ONE_DAD_PHONE_4_C_1,
	ONE_DAD_PHONE_4_C_2,
	ONE_DAD_PHONE_4_C_3,
	ONE_DAD_PHONE_5,
	ONE_DAD_PHONE_6,
	ONE_DAD_PHONE_6_A,
	ONE_DAD_PHONE_6_B,
	ONE_DAD_PHONE_7,
	ONE_DAD_PHONE_8,
	ONE_DAD_PHONE_9,
};

enum TextTensionType
{
	NORMAL_TENSION,
	LOW_TENSION,
	HIGH_TENSION,
	FATAL_TENSION,
};

struct TextDTO
{
	char* text = nullptr;
	int8_t playerTensionDelta = 0;
	TextTensionType tensionType = NORMAL_TENSION;

	TextDTO(char* text, int8_t playerTensionDelta = 0, TextTensionType tensionType = NORMAL_TENSION)
	{
		this->text = text;
		this->playerTensionDelta = playerTensionDelta;
		this->tensionType = tensionType;
	}
};

TextDTO getTextInfo(TextType textTye);